### PR TITLE
if function with int and double parameters

### LINKED ISSUE #42: if function with int and double parameters
When using the if function in compiled mode I get the error: 
'cannot be evaluated due this error: Argument types do not match'
 with expressions like
`if(true, 1, 0.0)`
While in interpreted mode this is evaluated correctly.
I tried to write an overload of the function in my context object that takes an int and double as parameters but that didn't do the trick.
Is it possible to add support for expressions like this?
Thanks

### PR DESCRIPTION
**Pull request by deltex80**
This update resolves #42 

Updated if function to allow for mixed int and double parameters.

### CODE REVIEW

File: src/NCalc/LambdaExpressionVistor.cs [hunk 1]
```diff
@@ -159,7 +159,9 @@ public override void Visit(Function function)
             switch (function.Identifier.Name.ToLowerInvariant())
             {
                 case "if":
-                    _result = L.Expression.Condition(args[0], args[1], args[2]);
+                    var if_arg1 = args[1].Type == typeof(bool) ? args[1] : L.Expression.Convert(args[1], typeof(double));
```
Comment (sklose) [inline src/NCalc/LambdaExpressionVistor.cs:162]: isn't this gonna break for `if(true, "hello", "world")`? `arg[1]` != bool -> convert(string, double). I think you need to check if both arg[1] and arg[2] are numeric and then cast it to the common denominator type

Comment (deltex80) [reply src/NCalc/LambdaExpressionVistor.cs:162]: Thank you sklose, yes you are right. I'll fix it as soon as i can.

Comment (deltex80) [reply src/NCalc/LambdaExpressionVistor.cs]: I updated the implementation and added more tests. Let me know what you think.

File: src/NCalc/LambdaExpressionVistor.cs [hunk 2]
```diff
@@ -159,7 +159,17 @@ public override void Visit(Function function)
             switch (function.Identifier.Name.ToLowerInvariant())
             {
                 case "if":
-                    _result = L.Expression.Condition(args[0], args[1], args[2]);
+                    var if_arg1 = args[1];
```
Comment (sklose) [inline src/NCalc/LambdaExpressionVistor.cs:162]: how about something like this, I think this would be more generic:

```csharp
var numberTypePriority = new Type[] { typeof(double), typeof(float), typeof(long), typeof(int), typeof(short) };
var index1 = numberTypePriority.IndexOf(args[1]);
var index2 = numberTypePriority.IndexOf(args[2]);
if (index1 >=0 && index2 >=0 && index1 != index2)
{
    args[1] = L.Expression.Convert(args[1], numberTypePriority[Math.Min(index1, index2));
    args[2] = L.Expression.Convert(args[2], numberTypePriority[Math.Min(index1, index2));
}

_result = L.Expression.Condition(args[0], args[1], args[2]);
```

Comment (deltex80) [reply src/NCalc/LambdaExpressionVistor.cs]: Updated. Thanks you, i appreciate your help.
