### PR TITLE
Throw ArgumentNullException when any parameters is null and null parameters are not allowed

### LINKED ISSUE #94: NullReferenceException when expression contains null parameter
I found a bug, which should be discussed: when expression contains null parameter and null parameters are not allowed a `NullReferenceException` is thrown. We don't need to get the most precise type if any of parameters is null

https://github.com/sklose/NCalc2/blob/4e0338cbf84236087b793430aa91287270a1df05/src/NCalc/Domain/EvaluationVisitor.cs#L68-L81

If the null parameters are not allowed we should throw `ArgumentNullException` instead, but it'll lead to breaking change. I think the best choice will be check first if any of parameters is null and don't throw any exceptions like `EvaluateOptions.AllowNullParameter` is specified. What do you think?

**Upd:** since if one or both null parameters in expression will cause `NullReferenceException` it will not be a breaking change and it's safe to throw `ArgumentNullException`, but a minor version increase should be done

### PR DESCRIPTION
**Pull request by Bykiev**
Closes #94

### CODE REVIEW

File: src/NCalc/Domain/EvaluationVisitor.cs [hunk 1]
```diff
@@ -74,7 +74,14 @@ public int CompareUsingMostPreciseType(object a, object b)
...
             var allowNull = (_options & EvaluateOptions.AllowNullParameter) == EvaluateOptions.AllowNullParameter;
 
-            Type mpt = allowNull ? GetMostPreciseType(a?.GetType(), b?.GetType()) ?? typeof(object) : GetMostPreciseType(a.GetType(), b.GetType());
+            if (!allowNull)
+            {
+                if (a == null)
+                    throw new ArgumentNullException(nameof(a));
+
+                if (b == null)
+                    throw new ArgumentNullException(nameof(b));
```
Comment (david-brink-talogy) [inline src/NCalc/Domain/EvaluationVisitor.cs:83]:
```
ArgumentNullException.ThrowIfNull(a, nameof(a));
ArgumentNullException.ThrowIfNull(b, nameof(b));
```

Comment (Bykiev) [reply src/NCalc/Domain/EvaluationVisitor.cs:83]: This is not supported by netstandard 2.0 and .net framework 4.5

**Review by david-brink-talogy — APPROVED** [review]
